# Numpy: семинар № 1

# Бибик Александр ПИ19-4

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

In [59]:
import numpy as np
import pandas as pd
lst = [1,3,5,9,20]

In [60]:
arr = np.array(lst)
print(arr)

[ 1  3  5  9 20]


In [61]:
arr ** 2

array([  1,   9,  25,  81, 400], dtype=int32)

In [62]:
arr + 2

array([ 3,  5,  7, 11, 22])

In [63]:
arr % 2

array([1, 1, 1, 1, 0], dtype=int32)

In [64]:
arr[1::2]

array([3, 9])

In [65]:
#Создание маски
mask = arr % 3 == 0
arr[mask]

array([3, 9])

In [66]:
arr = np.arange(20).reshape(5, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [67]:
#Выбрать по 3 
arr[1:3, -1]

array([ 7, 11])

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.load_txt`. Выведите на экран первые 5 строк массива.

In [68]:
data = np.loadtxt("C:/Users/Александр/Downloads/minutes_n_ingredients.csv",dtype=int, delimiter=",", skiprows=1)
print(data[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [69]:
# минимум, максимум и медиана для первого столбца(0)
col = 1
print(f"Мин: {np.min(data[:, col])}\nМакс:{np.max(data[:, col])}\nМедиана:{np.median(data[:, col])}\n")

# минимум, максимум и медиана для третьего столбца(2)
col = 2
print(f"Мин: {np.min(data[:, col])}\nМакс:{np.max(data[:, col])}\nМедиана:{np.median(data[:, col])}\n")

Мин: 0
Макс:2147483647
Медиана:40.0

Мин: 1
Макс:39
Медиана:9.0



3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [70]:
# Квантиль — значение, которое заданная случайная величина не превышает с фиксированной вероятностью

value = 0.75
q = np.quantile(data[:,1], value)
mask = data[:,1] <= q
data[mask]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [ 43407,     35,      7],
       [498432,     65,     15],
       [370915,      5,      4]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [71]:
noneValue=np.count_nonzero(data[:,1] == 0)
print(noneValue)

#заменяем нулевые значения в данном столбце на 1
data[:,1][data[:,1] == 0] = 1

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [72]:
u = np.unique(data[:, 1:2], axis=0).shape[0]
u

655

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [73]:
unique, counts = np.unique(data[:, 2], return_counts=True)
print(f"Всего уникальных: {len(unique)}")
dict(zip(counts,unique))

Всего уникальных: 37


{13: 1,
 926: 2,
 2895: 3,
 5515: 4,
 7913: 5,
 9376: 6,
 10628: 7,
 10951: 8,
 10585: 9,
 9591: 10,
 8297: 11,
 6605: 12,
 4997: 13,
 3663: 14,
 2595: 15,
 1767: 16,
 1246: 17,
 790: 18,
 573: 19,
 376: 20,
 217: 21,
 161: 22,
 105: 23,
 69: 24,
 50: 25,
 28: 26,
 16: 28,
 12: 30,
 3: 35,
 1: 39,
 2: 33}

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [74]:
ndarray = data[data[:,2] <= 5]
ndarray

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [75]:
ingredientsPerMinute = (data[:,2] / data[:,1])
print(ingredientsPerMinute)
np.max(ingredientsPerMinute)

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]


24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [76]:
top = np.argsort(data[:,1])[:-101:-1]
resultTop = data[top]
np.mean(resultTop[:,2])

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [77]:
data[np.random.randint(data.shape[0], size=10)]

array([[ 14179,     20,      7],
       [ 89828,    375,     12],
       [ 31787,     15,      8],
       [126710,     23,      9],
       [324496,     60,      7],
       [476010,      5,     11],
       [212608,     22,      9],
       [ 59362,     70,     11],
       [411501,     50,      4],
       [106576,     10,      4]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [78]:
average = data[ np.mean(arr[:,2]) > data[:,2] ]
average.shape[0] / data.shape[0] * 100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [79]:
# c_ преобразует срез в столбец, а последовательности соединяет вдоль второй оси

ez = (data[:,1] <= 20) & (data[:,2] <= 5)
arrEz = np.c_[data,ez]
arrEz

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [80]:
arrEz[ arrEz[ :, 3] == 1 ].shape[0] / arrEz.shape[0] * 100

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.